# Datatype

## 1. Numeric

### 1. 1. Integer types
| Type      | Storage<br>(Byte) | Minimum<br>Value<br>Signed | Minimum<br>Value<br>Unsigned | Maximum<br>Value<br>Signed | Maximum<br>Value<br>Unsigned |
|-----------|---------------:|---------------------:|-----------------------:|---------------------:|-----------------------:|
| TINYINT   | 1              | -128                 | 0                      | 127                  | 255                    |
| SMALLINT  | 2              | -32768               | 0                      | 32767                | 65535                  |
| MEDIUMINT | 3              | -8388608             | 0                      | 8388607              | 16777215               |
| INT       | 4              | -2147483648          | 0                      | 2147483647           | 4294967295             |
| BIGINT    | 8              | -2^63                | 0                      | 2^63-1               | 2^64-1                 |


### 1. 2. Fixed-point types
`DECIMAL(M, D)`  
`NUMERIC(M, D)`
- `M` : number of significant digits that are stored for values(precision)
- `D` : number of digits that can be stored following the decimal point (scale)

ex)
DECIMAL(5,2) can store any value with **five digits** and **two decimals**, so values that can be stored in the salary column range from -999.99 to 999.99.

### 1. 3. Floating-point types
The FLOAT and DOUBLE types represent approximate numeric data values in byte. Fxied-point `(M, D)` is also applicable.
- `FLOAT` : 4 byte
- `DOUBLE` : 8 byte

### 1. 4. Bit value type
Stores bit values  
`BIT(M)` enables storage of M-bit values. M can range from 1 to 64.


<br>

## 2. Date & Time

### 2. 1. `DATE`
`YYYY-MM-DD` : Stores date data.

### 2. 2. `DATETIME`
`YYYY-MM-DD HH:MM:SS` : Stores date and time data.

### 2. 3. `TIMESTAMP`
`YYYY-MM-DD HH:MM:SS` : Stores data and time data. If there are no input, timestamp data automatically stores current date and time.

### 2. 4. `TIME`
`HH:MM:SS` : Stores time data.

### 2. 5. `YEAR`
`YEAR(2)` : Stores year in two digits  
`YEAR(4)` : Stores year in two digits  

<br>

## 3. String

### 3. 1. `CHAR` & `VARCHAR`

- `CHAR` : CHAR column is fixed to the length that you declare when you create the table. The length can be any value from 0 to 255.
- `VARCHAR` : Variable-length strings. The length can be specified as a value from 0 to 65,535.

| Value      | CHAR(4) | Storage Required | VARCHAR(4) | Storage Required |
|:-----------|:--------|:----------------:|:-----------|:-----------------|
| ''         | '    '  | 4 bytes          | ''         | 1 byte           |
| 'ab'       | 'ab  '  | 4 bytes          | 'ab'       | 3 bytes          |
| 'abcd'     | 'abcd'  | 4 bytes          | 'abcd'     | 5 bytes          |
| 'abcdefgh' | 'abcd'  | 4 bytes          | 'abcd'     | 5 bytes          |

### 3. 2. `TEXT`

Unlike `CHAR` or `VARCHAR`, `TEXT` is specified when storing long length string.

<br>

<br>

# Constraint

Each column are set with constraint

### 1. `NOT NULL`
- Specifies that column can not contain any NULL value. MySQL NOT NULL can be used to CREATE and ALTER a table.

### 2. `UNIQUE`
- Does not allow duplicate value. The UNIQUE constraint maintains the uniqueness of a column in a table. More than one UNIQUE column can be used in a table.

### 3. `PRIMARY KEY`
- Meets both `NOT NULL` and `UNIQUE` constraints. This constraint is only allowed once on one column per table.
- Creates a unique index for accessing the table faster.

### 4. `FOREIGN KEY`
- Creates a link between two tables by one specific column of both tables.
- Specified column in one table must be a PRIMARY KEY and referred by the column of another table known as FOREIGN KEY.

### 5. `DEFAULT`
- If no value is supplied to a column, then the column gets the value set as DEFAULT.

### 6. `AUTO_INCREMENT`
- Increases the value of that column by 1 automatically, each time a new record is added.