In [1]:
from selenium import webdriver
import pandas as pd

In [27]:
df = pd.DataFrame(columns=['Ranking', 'Club', 'Pl', 'W', 'D', 'L', 'GD', 'Pts'])

In [34]:
def epl_table():
    
    driver = webdriver.Chrome()
    driver.get('https://www.premierleague.com/tables')
    
    try:
        driver.find_element_by_css_selector("#advertClose").click()
    except:
        print("no layer")
    
    teams = driver.find_elements_by_css_selector(".allTablesContainer table > tbody > tr:not(.expandable)")
    
    
    
    for idx, team in enumerate(teams):
        
        ranking = team.find_element_by_css_selector("td > .value")
        club = team.find_element_by_css_selector(".team .long")
        play = team.find_element_by_css_selector("td:nth-child(4)")
        win = team.find_element_by_css_selector("td:nth-child(5)")
        draw = team.find_element_by_css_selector("td:nth-child(6)")
        lose = team.find_element_by_css_selector("td:nth-child(7)")
        goal = team.find_element_by_css_selector("td:nth-child(10)")
        pts = team.find_element_by_css_selector(".points")
        data = {"Ranking" : ranking.text, 
                "Club" : club.text, 
                "Pl" : play.text,
                "W" : win.text,
                "D" : draw.text,
                "L" : lose.text,
                "GD": goal.text, 
                "Pts": pts.text }

        df.loc[len(df)] = data
        
        if idx == 19:
            break
    
    df.set_index('Ranking', inplace=True)
    df.to_csv('epl_table')
    
    return "File generated !"

In [35]:
epl_table()

no layer

'File generated !'

In [37]:
data = pd.read_csv('epl_table', index_col = 0)

In [38]:
data

                             Club  Pl   W   D   L  GD  Pts
Ranking
1                 Manchester City  27  23   3   1  59   72
2               Manchester United  28  18   5   5  33   59
3                       Liverpool  28  16   9   3  33   57
4               Tottenham Hotspur  28  16   7   5  29   55
5                         Chelsea  28  16   5   7  25   53
6                         Arsenal  27  13   6   8  15   45
7                         Burnley  28   9  10   9  -3   37
8                  Leicester City  28   9   9  10  -1   36
9                         Everton  28   9   7  12 -15   34
10                        Watford  28   9   6  13  -9   33
11                    Bournemouth  28   8   8  12 -10   32
12       Brighton and Hove Albion  28   7  10  11 -11   31
13                West Ham United  28   7   9  12 -15   30
14              Huddersfield Town  28   8   6  14 -23   30
15               Newcastle United  28   7   8  13 -11   29
16                    Southampton  28   5  12  11 -12   27
17                 Crystal Palace  28   6   9  13 -18   27
18                   Swansea City  28   7   6  15 -20   27
19                     Stoke City  28   6   8  14 -26   26
20           West Bromwich Albion  28   3  11  14 -20   20
1                 Manchester City  27  23   3   1  59   72
2               Manchester United  28  18   5   5  33   59
3                       Liverpool  28  16   9   3  33   57
4               Tottenham Hotspur  28  16   7   5  29   55
5                         Chelsea  28  16   5   7  25   53
6                         Arsenal  27  13   6   8  15   45
7                         Burnley  28   9  10   9  -3   37
8                  Leicester City  28   9   9  10  -1   36
9                         Everton  28   9   7  12 -15   34
10                        Watford  28   9   6  13  -9   33
11                    Bournemouth  28   8   8  12 -10   32
12       Brighton and Hove Albion  28   7  10  11 -11   31
13                West Ham United  28   7   9  12 -15   30
14              Huddersfield Town  28   8   6  14 -23   30
15               Newcastle United  28   7   8  13 -11   29
16                    Southampton  28   5  12  11 -12   27
17                 Crystal Palace  28   6   9  13 -18   27
18                   Swansea City  28   7   6  15 -20   27
19                     Stoke City  28   6   8  14 -26   26
20           West Bromwich Albion  28   3  11  14 -20   20